create database saasant; 
USE SAASANT; 
SHOW TABLES;
CREATE TABLE STUDENT_INFO (STU_ID bigint primary key,
 STU_NAME VARCHAR(30),MARK1 INT, MARK2 INT, MARK3 INT, TOTAL INT,
 AVERAGE float);
 
 ALTER TABLE STUDENT_INFO RENAME COLUMN STU_NAME TO STUDENT_NAME;
 ALTER TABLE STUDENT_INFO MODIFY AVERAGE INT;
 alter table student_info modify stu_id bigint primary key; 
 
 COMMIT;
 
 DESC STUDENT_INFO;
 DROP TABLE STUDENT_INFO;
 
 -- COMMIT --> IT CONFIRMS THE COMMAND 
 
 INSERT INTO STUDENT_INFO 
 (STU_ID, STU_NAME, MARK1, MARK2,MARK3, TOTAL, AVERAGE) valueS
 (20200103,'Sandya', 98, 80,89, 260,85);
 
 INSERT INTO STUDENT_INFO 
 (STU_ID, STU_NAME, MARK1, MARK2,MARK3, TOTAL, AVERAGE) valueS
 (20200104,'Agila', 88, 99,95, 250,60);
 
 ROLLBACK;
 
 COMMIT;
 
 SELECT * FROM STUDENT_INFO; -- * --> All columns
 
 select stu_id, stu_name, total, average from student_info;
 
 select * from student_info where total >= 260 or total <= 270 ;
 
 update student_info set average= 83 where stu_id=20200104; 
 
 truncate table student_info;
 
 delete from student_info  where stu_id=20200104; 
 
 drop table student_info;



-- stu_id, DoorNO, AddressLine1, AddressLine2, City, State, Zip

CREATE TABLE STUDENT_ADDRESS_INFO (STU_ID BIGINT ,addr_type varchar(10), DOOR_NO VARCHAR(10), 
ADDR1 VARCHAR(30), ADDR2 VARCHAR(30), CITY VARCHAR(30), STATE VARCHAR(20), ZIP INT, foreign key(STU_ID) references STUDENT_INFO(STU_ID));

INSERT INTO STUDENT_ADDRESS_INFO (STU_ID,DOOR_NO,ADDR1,ADDR2,CITY,STATE,ZIP) 
VALUES(20200103, '45A','1ST STREET','SAIBABA COLONY','CHENNAI','TN',600100);

INSERT INTO STUDENT_ADDRESS_INFO (STU_ID,DOOR_NO,ADDR1,ADDR2,CITY,STATE,ZIP) 
VALUES(20200104, '40A','2nd STREET','SAI COLONY','CHENNAI','TN',600120);


INSERT INTO STUDENT_ADDRESS_INFO (STU_ID,DOOR_NO,ADDR1,ADDR2,CITY,STATE,ZIP) 
VALUES(20210202, '55j','Main STREET','BABA COLONY','MADURAI','TN',625098);


INSERT INTO STUDENT_ADDRESS_INFO (STU_ID,DOOR_NO,ADDR1,ADDR2,CITY,STATE,ZIP) 
VALUES(20220109, '56','Dubai STREET','Dubai COLONY','COIMBATORE','TN',641035);

SELECT * FROM STUDENT_ADDRESS_INFO;

truncate table STUDENT_ADDRESS_INFO;

SELECT SI.STU_ID,SI.STU_NAME,SAI.CITY   
FROM STUDENT_INFO SI  JOIN STUDENT_ADDRESS_INFO SAI ON 
SI.STU_ID=SAI.STU_ID WHERE SAI.CITY='CHENNAI'; 


SELECT *   
FROM STUDENT_INFO SI  JOIN STUDENT_ADDRESS_INFO SAI ON 
SI.STU_ID=SAI.STU_ID WHERE SI.STU_ID=20200103; 


 